### ISSUE TITLE
避免頁面載入時觸發動畫，動畫觸發

### ISSUE THREAD

**Issue by U1320100568** [U1320100568/note#14]
狀況：component預設class = hide，表示一開始為收起來，第一次載入頁面觸發 hide animation( height: 100 to 1 )，導致載入時會有短暫的收合動畫。   
   
[How to prevent css keyframe animation to run on page load?](https://stackoverflow.com/questions/27938900/how-to-prevent-css-keyframe-animation-to-run-on-page-load)
解決方法：  
1. 一開始不要給class，等到觸發hide時才給。
2. 在root 擋下所有的 animate，完成 mount 後在開通animate，[ref](https://stackoverflow.com/a/38296629/13797221)
```scss
&.preload *{
    animation-duration: 0s !important;
    transition:background-color 0s, opacity 0s, color 0s, width 0s, height 0s, padding 0s, margin 0s !important;
}
```
